import Head from "next/head";
import styles from "../../../styles/Auth.module.css";

export default function Register() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.flexContainer}>
        <div className={styles.flexLeft}>
          <div>
            Left<br></br> Hand.
          </div>
        </div>
        <div className={styles.flexRight}>
          <div className={styles.card}>
            <p className={styles.head}>Daftar</p>
            <div className={styles.input}>
              <div>
                <label for="name">Nama</label>
                <input type="name" id="name" placeholder="Nama Lengkap"></input>
              </div>
              <div>
                <label for="email">Email</label>
                <input
                  type="email"
                  id="email"
                  placeholder="Contoh: johndee@gmail.com"
                ></input>
              </div>
              <div>
                <label for="password">Password</label>
                <input
                  type="password"
                  id="password"
                  placeholder="Masukkan Password"
                ></input>
              </div>
            </div>
            <button type="button" className={styles.button}>
              Daftar
            </button>
            <p className={styles.footer}>
              Sudah punya akun? <a href="login">Masuk disini</a>
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
