import { useState } from "react";
import BackButton from "./components/back-button/BackButton";
import NavBar from "./components/navbar"
import ProductForm from "./components/product-form/ProductForm";
import axios from "axios";

import { useFormik } from 'formik';
import * as Yup from 'yup';
import Head from "next/head";
import { postRequest } from "../../api/apiConfig";

const AddProduct = () => {
    const [product, setProduct] = useState([])
    const [images, setImages] = useState([])

    const storeProduct = async (form) => {
        try {
            const config = {
                headers: {
                    'content-type': 'multipart/form-data',
                    'Authorization': localStorage.getItem('token').substring(7)
                    // 'Authorization': localStorage.getItem('token')
                }
            }

            console.log(form);

            const response = await axios.post('https://pa-be-k3.herokuapp.com/api/product/create', form, config)
            // const response = await postRequest('/product/create', form, 1000)
            // setRefetch(response.data.data)
            console.log(response.data.data);

        } catch (error) {
            console.log(error)
        }
    }

    // console.log(localStorage.getItem('token').substring(7));

    return (
        <div>
            <Head>
                <title>Add Product</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar />
            <div className="container">
                <div className="row justify-content-center">
                    <BackButton />
                    <ProductForm setProduct={setProduct} setImages={setImages} images={images} storeProduct={storeProduct} />
                </div>
            </div>
        </div>
    )
}

export default AddProduct;