import { useEffect, useState } from "react";
import BackButton from "./components/back-button/BackButton";
import NavBar from "./components/navbar"
import ProductForm from "./components/product-form/ProductForm";
import axios from "axios";
import Head from "next/head";

const AddProduct = () => {
    const [categories, setCategories] = useState([])
    const [refetch, setRefetch] = useState([]);

    const storeProduct = async (form) => {
        try {
            const config = {
                headers: {
                    'Content-Type': `multipart/form-data; boundary=${form._boundary}`,
                    'Access-Control-Allow-Origin': '*',
                    'Authorization': localStorage.getItem('token').substring(7),
                },
            }
            console.log(form);
            const response = await axios.post('https://pa-be-k3.herokuapp.com/api/product/create', form, config)
            // setRefetch(response.data.data)
            console.log(response.data.data);

        } catch (error) {
            console.log(error)
        }
    }
    const storeCategory = async (form) => {
        try {
            console.log(form);
            const response = await axios.post('https://pa-be-k3.herokuapp.com/api/category/create', form)
            setRefetch(response.data.data)
            console.log(response.data.data);

        } catch (error) {
            console.log(error)
        }
    }

    const getCategoriesData = async () => {
        try {
            const response = await axios.get('https://pa-be-k3.herokuapp.com/api/category/list')
            // console.log(response.data.data);
            return setCategories(response.data.data)
        } catch (error) {
            console.log(error)
        }
    }

    useEffect(() => {
        getCategoriesData();
    }, [refetch]);

    return (
        <div>
            <Head>
                <title>Add Product</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar />
            <div className="container">
                <div className="row justify-content-center">
                    <BackButton />
                    <ProductForm
                        storeProduct={storeProduct}
                        categories={categories}
                        storeCategory={storeCategory}
                    />
                </div>
            </div>
        </div>
    )
}

export default AddProduct;