import Head from "next/head";
import Image from "next/image";
import styles from "../../../styles/Auth.module.css";
import googleImage from "../../../public/images/google.png";
import facebookImage from "../../../public/images/facebook.png";

export default function Login() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.flexContainer}>
        <div className={styles.flexLeft}>
          <div>
            Left<br></br> Hand.
          </div>
        </div>
        <div className={styles.flexRight}>
          <div className={styles.card}>
            <p className={styles.head}>Masuk</p>
            <div className={styles.input}>
              <div>
                <label for="email">Email</label>
                <input
                  type="email"
                  id="email"
                  placeholder="Contoh: johndee@gmail.com"
                ></input>
              </div>
              <div>
                <label for="password">Password</label>
                <input
                  type="password"
                  id="password"
                  placeholder="Masukkan Password"
                ></input>
              </div>
            </div>
            <p className={styles.forget}>
              <a href="forget-password">Lupa password?</a>
            </p>
            <button type="button" className={styles.button}>
              Masuk
            </button>
            <div className={styles.line}>
              <hr />
              <span>or</span>
              <hr />
            </div>
            <div className={styles.buttonAuth}>
              <button type="button" className={styles.facebook}>
                <Image src={facebookImage} height={20} width={20}></Image>
                Facebook
              </button>
              <button type="button" className={styles.auth}>
                <Image src={googleImage} height={20} width={20}></Image> Google
              </button>
            </div>
            <div className={styles.line2}>
              <hr></hr>
            </div>
            <p className={styles.footer}>
              Belum punya akun? <a href="register">Daftar disini</a>
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
