import { useEffect, useState } from "react";
import BackButton from "./components/back-button/BackButton";
import NavBar from "./components/navbar"
import axios from "axios";
import Head from "next/head";
import OfferForm from "./components/offer-form/OfferForm";

const ProductOffer = () => {

    return (
        <div>
            <Head>
                <title>Product Offer</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar />
            <div className="container">
                <div className="row justify-content-center">
                    <BackButton />
                    <OfferForm />
                </div>
            </div>
        </div>
    )
}

export default ProductOffer;