import Head from "next/head";
import styles from "../../../styles/Auth.module.css";

export default function Login() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Password Baru</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.flexContainer}>
        <div className={styles.flexLeft}>
          <div>
            Left<br></br> Hand.
          </div>
        </div>
        <div className={styles.flexRight}>
          <div className={styles.card}>
            <p className={styles.head}>Password Baru</p>
            <div className={styles.input}>
              <div>
                <label for="password">Password</label>
                <input
                  type="password"
                  id="password"
                  placeholder="Masukkan Password"
                ></input>
              </div>
              <div>
                <label for="confirmPassword">Konfirmasi Password</label>
                <input
                  type="password"
                  id="confirmPassword"
                  placeholder="Masukkan Password Konfirmasi"
                ></input>
              </div>
            </div>
            <button type="button" className={styles.button}>
              Buat Password Baru
            </button>
            <p className={styles.footer}>
              <a href="../login">kembali</a>
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
